// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjSkTle5jVf-B5l-IJ-wl-UjyENMdk8Fg',
    appId: '1:776538734644:web:40571b26f1b06d0e398a61',
    messagingSenderId: '776538734644',
    projectId: 'piramid-game-ifpr',
    authDomain: 'piramid-game-ifpr.firebaseapp.com',
    storageBucket: 'piramid-game-ifpr.firebasestorage.app',
    measurementId: 'G-76VZ1SZ17X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxl9gFSDDWH2jAagCyTmMon0WRJq7kjfc',
    appId: '1:776538734644:android:f62c223bc83ce7da398a61',
    messagingSenderId: '776538734644',
    projectId: 'piramid-game-ifpr',
    storageBucket: 'piramid-game-ifpr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCna5SJPdspEwTUcXONzw8EBZCSlFSclQg',
    appId: '1:776538734644:ios:84d10193e91a9f85398a61',
    messagingSenderId: '776538734644',
    projectId: 'piramid-game-ifpr',
    storageBucket: 'piramid-game-ifpr.firebasestorage.app',
    iosClientId: '776538734644-9jlnano0kia7hdaknvevvt7s90cb3gdh.apps.googleusercontent.com',
    iosBundleId: 'com.example.piramidGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCna5SJPdspEwTUcXONzw8EBZCSlFSclQg',
    appId: '1:776538734644:ios:84d10193e91a9f85398a61',
    messagingSenderId: '776538734644',
    projectId: 'piramid-game-ifpr',
    storageBucket: 'piramid-game-ifpr.firebasestorage.app',
    iosClientId: '776538734644-9jlnano0kia7hdaknvevvt7s90cb3gdh.apps.googleusercontent.com',
    iosBundleId: 'com.example.piramidGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjSkTle5jVf-B5l-IJ-wl-UjyENMdk8Fg',
    appId: '1:776538734644:web:fa67abdf6ecf8ee5398a61',
    messagingSenderId: '776538734644',
    projectId: 'piramid-game-ifpr',
    authDomain: 'piramid-game-ifpr.firebaseapp.com',
    storageBucket: 'piramid-game-ifpr.firebasestorage.app',
    measurementId: 'G-6V2B44MYGN',
  );
}
